### ISSUE TITLE
Unable to get Course ID anymore

### ISSUE THREAD

**Issue by helloanurag** [joeytyndale/gco-extension#1]
The extension is not pulling the Course ID anymore. I checked with different course pages and all I get is ":s" in the pop-up. It seems that the source code was changed on the course page.
Can you please have a look?
![image](https://user-images.githubusercontent.com/48911364/93414634-4fd4a780-f8bf-11ea-80cb-d5c4815fdfa8.png)

Thanks!

**Comment by helloanurag** [comment]
This seems to be fixed itself.
Closing this!

**Comment by helloanurag** [comment]
@joeytyndale 
Unfortunately, this issue is back again. This is what I get when I try to get the course ID from the course page:
![image](https://user-images.githubusercontent.com/48911364/94532078-068b3d00-025b-11eb-9cb8-310abb5ad943.png)

**Comment by joeytyndale** [comment]
@helloanurag your new work around works much better than this tool. I'd suggest we retire the tool.

**Comment by helloanurag** [comment]
@joeytyndale 
Sure though it was nice having the extension as it used to pull the live data. The current module gets update on a weekly basis and in case if someone types in a course name which was released in the same week, it won't show any details.
Thank you :)
